### ISSUE TITLE
[FEATURE] 전세사기 예방 부분 구현

### ISSUE THREAD

**Issue by seongikx** [kakao-tech-campus-2nd-step3/Team11_FE#104]
## 기능 설명 
    전세사기 예방 파트 페이지들을 구현합니다.
    
## 마감 일자
    11월 14일 까지

## TODO
- [x] 설문조사 페이지 구현
- [x] 결과 페이지 구현
- [x] 자가 진단 페이지 구현
- [x] 경매 이후 페이지 구현
- [x] 카카오톡 채널 추가 페이지 구현
- [x] 보증 보험 가입 페이지 구현
