### ISSUE TITLE
[FEATURE] 전세 피해 예방 step1 페이지 구현

### ISSUE THREAD

**Issue by yunseong0404** [kakao-tech-campus-2nd-step3/Team11_FE#42]
## 기능 설명 
    전세 피해 예방 step1 페이지 구현를 구현합니다.
    
## 마감 일자
    10월 11일까지 

## TODO
- [x] 현재상황 진행도 컴포넌트 구현
- [x] 검색 컴포넌트 구현
- [x] 버튼 컴포넌트 구현
